### PR TITLE
Fix parsing of random link from coding love

### PR DESCRIPTION
**Pull request by ollitapa**
Seems like the link place on the site changed a little. Also added a better link to the site.

### CODE REVIEW

**Comment by valeriomazzeo** [comment]
@ollitapa - thanks for the PR!

I have just merged #12. If you can update your branch with this new changes from master, CI should be green and I'll be happy to merge it.

**Comment by ollitapa** [comment]
I rebased the branch. Had to also add missing update on the Gemfile.lock, since CI would not pass without it?

**Comment by valeriomazzeo** [comment]
I think that's because you didn't have to change https://github.com/valeriomazzeo/danger-the_coding_love/pull/11/files#diff-8aaeeaa3a4c26c92f3666031291f59acR4

I can bump that when releasing a new version. Anyway it's ok. 👍

**Comment by ollitapa** [comment]
Ah, okay, sorry about that.

**Comment by valeriomazzeo** [comment]
Not a problem at all, thanks for the pull request. I have just released `v0.0.8`, can you try to update and double check everything's fine?

**Comment by ollitapa** [comment]
Screenshot 2020-04-15 at 13 19 53

Seems to work 🥳

**Pull request merged**
